### ISSUE TITLE
System.InvalidOperationException: UserId not found

### ISSUE THREAD

**Issue by emaish** [aspnetboilerplate/module-zero#107]
Dear Halil,
i got this exception when i try to use UserManager.IsInRoleAsync or UserManager.GetRoleAsync

System.InvalidOperationException: UserId not found.     at Microsoft.AspNet.Identity.UserManager`2.<GetRolesAsync>d__ac.MoveNext()  ---

it was working long time ago in old versions.

**Comment by hikalkan** [comment]
Maybe user user was deleted or he has another TenantId than the active one? Can you check the generated SQL in SQL Profiler and share with us.

**Comment by emaish** [comment]
i forget to mention, this error occur when i try to use it in the Login action in Account Controller, if user is logged in the method is working with no problem.

**Comment by hikalkan** [comment]
Then it's pretty normal. It's because of data filters.
IsInRoleAsync methods gets two parameters:
1. UserId
2. RoleName

In a multi-tenant app, same role name (say, "Admin" role) can be repeated in different tenants. So, UserManager can not work without TenantId. So, in order to obtain a tenant id, a user should be login. Thus, we can use this login user's tenant id. Otherwise, how can we know which TenantId to use?

So, you should be a tenant id, otherwise can not use usermanager. if you know it but user is not logged in, then you can set TenantId filter parameter before using user manager.

**Comment by emaish** [comment]
Thank you :)

**Comment by hikalkan** [comment]
Maybe usermanager can be smart to get user first from database then get his tenant id and use it. But, it's not possible normally since this code in IdentityFramework. We may override and change it. Anyway, I think you understood the reason.

**Comment by emaish** [comment]
yes it could be done automatically, but i understand the reason and will make it work, thank you :)
