### ISSUE TITLE
Might want to add unique constraint on AbpRole TenantId and Name

### ISSUE THREAD

**Issue by rahulbpatel** [aspnetboilerplate/module-zero#110]
I inadvertently wrote some incorrect DB seed code that added duplicate role names.   Was wondering if there was a unique constraint in the database but IX_TenantId_Name on table AbpRoles is Non-Unique.  Maybe something like this is needed?

http://stackoverflow.com/questions/18889218/unique-key-constraints-for-multiple-columns-in-entity-framework

**Comment by hikalkan** [comment]
There is a problem with unique index. Because Role is ISoftDelete (not deleted from database actually). That means you can delete a role with name "Admin" and create another role with same name "Admin" for same Tenant.

Creating an index is good, but it should not be unique. UserManager ensures uniqueness.

BTW, we can not add [Index] property to entities since it's EF specific and requires referencing EF from Domain layer. We may make it on model creating.

**Comment by hikalkan** [comment]
I'm closing this. Follow this one: https://github.com/aspnetboilerplate/module-zero/issues/140

**Comment by majumajid** [comment]
Now (EF 6.1 onwards )you can easily have unique constrains ,

[Index("TitleIndex", IsUnique = true)]
 public string Title { get; set; }
