### ISSUE TITLE
CreateOrMigrateForTenant Not working

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#226]
@karen-hikesupport:

Hi,

we have setup the two context one for Hostcontext and other TenantContext but when we create new Tenant with connectionstring, it is not creating database with tenant. can u just tell me how?

**Comment by hikalkan** [comment]
Hi,

Can you share your class created for Tenant and derived from AbpZeroDbMigrator?

**Comment by karen-hikesupport** [comment]
#
[HikePOS.EntityFramework.zip](https://github.com/aspnetboilerplate/module-zero/files/329345/HikePOS.EntityFramework.zip)

**Comment by karen-hikesupport** [comment]
i have attached our whole layer code as well

**Comment by karen-hikesupport** [comment]
Hi
i am waiting for your reply !

**Comment by ismcagdas** [comment]
Hi,

As far as i can see, you have a single DbMigrator and it's for your Host DbContext (HikePOSDbContext).

You need to create another DbMigrator for your TenantDbContext.

Please see this forum topic http://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2756&p=6402&hilit=DbMigrator#p6402

**Comment by karen-hikesupport** [comment]
Hi,

Just See it on Tenant "TenantMigrations" Folder i have created another Migration for Tenantdbcontext as you said

**Comment by karen-hikesupport** [comment]
Hi,
please reply to us we are waiting,

**Comment by ismcagdas** [comment]
have you read and implement the steps on the forum topic i have send you above.

**Comment by hikalkan** [comment]
@karen-hikesupport your dbcontext implementation is already wrong.
Why your TenantDbContext inherits AbpDbContext? It should inherit from AbpZeroDbContext or AbpZeroTenantDbContext (if you don't want to include host tables to tenant databases) if you want to get module-zero tables in your tenant database.
Also, HikePOSDbContext may inherit from AbpZeroHostDbContext, instead of AbpZeroDbContext.

Please explain what you are trying to do in detailed.

**Comment by karen-hikesupport** [comment]
Hi,
Thanks for the help,
we need to database one for the Masterdatacontext they contains host tables like Abp Tenant,Abp User and all things..., and other one is TenantdbContext contains out application table (No host Table). and we need that when we createanyTenant so automatcally migrate the Tenatdatacontext with new database using connectionstring. is it possible and if yes how?

**Comment by ismcagdas** [comment]
Yes, it is possible.

Can you share your tenant creation code ?

On the other hand, you should store Tenant's users in the tenant database. As Halil said, your TenantDbContext should inherit from AbpZeroDbContext  or AbpZeroTenantDbContext. 

Think such a scenario,

You have a Product table and it contains CreationUserId field in Tenant database.
If you want to get a list of products with Creation user's name, you will need to join two different databases.

**Comment by karen-hikesupport** [comment]
Hi, 

Thanks for the Reply,

you mean to say as we need to create user and roles on Both Databases, TenantDbcontext and Hostdbcontext, so how can we manage user and role on both side? i am little confuse here.

Here if we use  AbpZeroTenantDbContext for TenantContext, so it is compulsary load inject Role and user entity and same as the in AbpZeroDbContext  (Tenant, Role ,User), can u give me idea, how can we perform overall ?

b'cse i would be clear in future will may be purchase you license :)

**Comment by ismcagdas** [comment]
No, actually.
If a user belongs to Host, it will be stored on the host database.
If a user belongs to a tenant, it will be stored on that tenant's database. There will be no duplicate records.

And yes, if you use AbpZeroTenantDbContext for TenantContext, all tables will be created for each tenant. Each tenant will have it's own roles, users etc. But Tenant databases will not contain Tenant table.

**Comment by hikalkan** [comment]
Shall we close this?

**Comment by softcial** [comment]
I know that this issue is closed but I'm having the same issue with the CreateOrMigrateForTenant.  I created the TenantContext based on AbpZeroTenantDbContext but now I don't know how to call if from the AbpZeroDbMigrator instance.  Unfortunately the link provided ismcagdas is broken and I haven't found a sample on how to do this.  Is there any available?

**Comment by acjh** [comment]
Updated link:
[https://forum.aspnetboilerplate.com/**viewtopic.php**?f=5&t=2756&p=6402&hilit=DbMigrator#p6402](https://forum.aspnetboilerplate.com/viewtopic.php?f=5&t=2756&p=6402&hilit=DbMigrator#p6402)

**Comment by softcial** [comment]
@acjh Thank you very much for your kind reply and for providing me with the updated link.  In my case thought the problem is that the CreateOrMigrateForTenant method is not working (I mean, it is not creating the database for the tenant even thought we have provided the connection string at the "Create tenant" feature)  We are using MySql on an Ubuntu environment.   Could that be the problem? (I mean, that creating the database automatically for a tenant in MySql is not currently supported).  This is the connection string we are setting when creating the tenant: Server=localhost;port=3306;Database=TENANTX;Uid=[USER ID];Pwd=[USER PASSWORD]; where TENANTX is the name we want for the database and [USER ID] and [PASSWORD] are the information for user authentication.  

Thanks in advance for your kind reply!

**Comment by ismcagdas** [comment]
@softcial are you using EF Core or EF 6.x ?

**Comment by hikalkan** [comment]
@danghuynhdaty this repository is forsaken. Please create a new issue on https://github.com/aspnetboilerplate/aspnetboilerplate and describe your issue in more details.
