### ISSUE TITLE
AbpZeroDbContext must be convertible to Microsoft.EntityFrameworkCore.DbContext

### ISSUE THREAD

**Issue by vdurante** [aspnetboilerplate/module-zero#233]
The following code, included in the website template, does not work once I integrated Module Zero with an Asp.Net Core application.

Running Abp.Zero.EntityFramework version 0.10.1

Apparently AbpZeroDbContext must derive from DbContext

EDIT > I am sorry, maybe Module Zero is not ready for Asp.Net Core yet?
```c#
/* MyAppDbContext.cs */
public class MyAppDbContext : AbpZeroDbContext<Tenant, Role, User>
{
    public MyAppDbContext(DbContextOptions<MyAppDbContext> options)
        : base(options)
    {
    }
}

/* DbContextOptionsConfigurer.cs */
public static class DbContextOptionsConfigurer
{
    public static void Configure(
        DbContextOptionsBuilder<MyAppDbContext> dbContextOptions, 
        string connectionString
        )
    {
        /* This is the single point to configure DbContextOptions for MyAppDbContext */
        dbContextOptions.UseSqlServer(connectionString);
    }
}

/* MyAppDbContextFactory.cs */
/* This class is needed to run "dotnet ef ..." commands from command line on development. Not used anywhere else */
public class MyAppDbContextFactory : IDbContextFactory<MyAppDbContext>
{
    public MyAppDbContext Create(DbContextFactoryOptions options)
    {
        var builder = new DbContextOptionsBuilder<MyAppDbContext>();
        var configuration = AppConfigurations.Get(WebContentDirectoryFinder.CalculateContentRootFolder());

        DbContextOptionsConfigurer.Configure(
            builder, 
            configuration.GetConnectionString(MyAppConsts.ConnectionStringName)
            );

        return new MyAppDbContext(builder.Options);
    }
}
```

**Comment by hikalkan** [comment]
Yes, it's not ready yet. Abp.Zero.EntityFramework package is for EF 6.x, not for EF Core. Actually, there is an EF Core contribution (https://github.com/aspnetboilerplate/module-zero/tree/dev/src/Abp.Zero.EntityFrameworkCore) but I did not published it yet since it's not tested.
One another problem is that ABP's EF Core integration currently does not support automatic data filters, which makes single db multi-tenancy and automatic soft delete filtering impossible (http://www.aspnetboilerplate.com/Pages/Documents/Entity-Framework-Core#missing-points)

**Comment by vdurante** [comment]
Thanks, sorry for disturbing.

**Comment by hikalkan** [comment]
Abp.Zero.EntityFrameworkCore package is published.
