### ISSUE TITLE
abp.zero.ldap email problem

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/module-zero#279]
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1638

**Comment by ismcagdas** [comment]
Hi @kimbendtsen,

Every time a user logs in with Ldap, the user information is updated, that's why I think you loose email information.

Is it possible that, the mentioned user might not have a email address on Ldap, or maybe you dont have permission to access email address information ?

Can you check that ?
You can use UserPrincipal.FindByIdentity to retrieve user's information from LDAP.

**Comment by kimbendtsen** [comment]
H @ismcagdas, you are right. We were using a test domain setup where the users did not have email addresses. After filling in the email addresses, the users can log in again. 

So apparently no issue afterall 👍 

I think it was difficult to get to the point where I could actually see that it was the email address missing. I ended up download all source code, remove the NuGet packages, adding references to the locally compiled dll's, adding the abp scripts directly in the source again. And then it would sometimes debug with source code in the abp dll's. 
It don't know if there is a easier method to do abp debugging? For this I could have done with abp.zero only, but I took everything as I wasn't sure what parts I needed to debug. 

Thanks.
