### ISSUE TITLE
UserFriendly Exceptions on Login don't throw

### ISSUE THREAD

**Issue by fireheadbr** [aspnetboilerplate/module-zero#31]
In the Login View, the userfriendly exceptions are not displayed. Even in the example of the project on GitHub. But on the project (demo online) it works.
The post are made by jquery with abp.ajax, how can i handle the messages errors like user/pass invalid and display them ?

**Comment by langman66** [comment]
Hi Diego,

Here's how I was able to get access to the success and error callbacks. This may not be the optimal way, but one that I could make work.  Also in this example I'm using mvc razor views and I'm not logged into my Angular SPA application.  My public facing website is MVC using ABP and then once authenticated and logged in, I'm using Angular SPA views/controllers, etc.

I did lots of trial and error attempting to get access to the deferred and promise objects from abp.ui.setBusy(), but wasn't able to for some reason.

Noticed in the code below I named "onSuccess" and "onError" callback functions, but those could have easily just been in-lined.

Here's the code I'm using in the login.js file.  For some reason the mvc account control is returning a 500 response code.
![invalid-login](https://cloud.githubusercontent.com/assets/3853763/6081003/f2c78692-ade3-11e4-9cdb-fac7e1baffb0.png)

 var deferred = null;

        abp.ui.setBusy(
            $('#LoginArea'),
            deferred = abp.ajax({               
                url: '/Account/Login',
                type: 'POST',
                success: onSuccess,
                error: onError,
                    data: JSON.stringify({
                        usernameOrEmailAddress: $('#EmailAddressInput').val(),
                        password: $('#PasswordInput').val(),
                        rememberMe: $('#RememberMeInput').is(':checked'),
                        tenancyName: 'Default'
                    })
                })
        );

        function onSuccess(data) {
            console.log('onSuccess');
        }

        function onError(data) {
            if (data && data.status === 500) {
                console.log('500 error code');
            }
            console.log('onError');
            abp.notify.error('We were unable to login using credentials provided.');

            $('#login-message-area').css('display', '');
            $('#login-message').text('We were unable to login you in.');

        }

Hope this helps,

Chris

**Comment by emaish** [comment]
If you use the login method code from example project, you get a 500 error because the login method threw exception when login failed, you may change this by returning a result with success of fail with additional info instead of threwing exeption, and use the return result to show a friendly message with respect to it

**Comment by emaish** [comment]
"Update with code"
If you use the login method code from example project, you get a 500 error because the login method threw exception when login failed, you have two solutions.
Solution: The error callback should accept three parameters, the third parameter will be your friendly message so the function from Chris will be 
```javascript
function onError(xhr, foo, friendlyError) {
        console.log('onError');
        abp.notify.error(friendlyError);

        $('#login-message-area').css('display', '');
        $('#login-message').text(friendlyError);
   }
```
Second Solution: you may change the login method to return a result with fail status with additional info instead of throwing exception, the will call abp function HandleData and will also call your error callback this can be done as following
```C#
return Json(new MvcAjaxResponse { Success = false, Error = new Abp.Web.Models.ErrorInfo(0, "Invalid user name or password") }); // 0 is the error code
```
but in this case you will use error call back with one parameter only, and Chris function will be
```javascript
function onError(data) {
        console.log('onError');
        abp.notify.error(data.message);

        $('#login-message-area').css('display', '');
        $('#login-message').text(data.message);
    }
```

**Comment by langman66** [comment]
Thanks Emaish for providing that additional guidance. This makes more sense to me now and I've changed my approach on Login and Registration to return MvcAjaxResponse.

**Comment by fireheadbr** [comment]
Guys, thanks 4 reply ! I tried to customize the error with friendly message, but it didn't work ! Now it's clear, thanks Emaish for the tip ! 
I just don't understand because on the demo online it seems to work natively with UFexception.

**Comment by emaish** [comment]
I'm glad it helped you :+1:  :)

**Comment by brendan-rice** [comment]
Thanks, this really helped.

**Comment by hmmdeif** [comment]
@fireheadbr @brendan-rice @langman66 @emaish You guys don't need to do this at all. The `UserFriendlyException` generates a proper MvcAjaxResponse through the [HandleException](https://github.com/aspnetboilerplate/aspnetboilerplate/blob/1537149b99a040f09c66a6ff863747e6940f218c/src/Abp.Web.Mvc/Web/Mvc/Controllers/AbpHandleErrorAttribute.cs) class inside Abp.

The reason you guys are not seeing anything is due to line 44. To resolve this, turn customErrors on in your web.config and then it'll start alerting instead of just throwing to the log!

**Comment by emaish** [comment]
close the issue please
