### ISSUE TITLE
about [UnitOfWork]

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/module-zero#310]
[OrganizationUnitManager](https://github.com/aspnetboilerplate/module-zero/blob/dev/src/Abp.Zero/Organizations/OrganizationUnitManager.cs#L34)

In the OrganizationUnitManager, Create, delete, Move method has [UnitOfWork] attribute, why update method does not have this property?

**Comment by hikalkan** [comment]
Hi,

Because it's not needed (not needed to be transactional) for Update, but others need.

**Comment by maliming** [comment]
hi @hikalkan 
Sorry, I did not fully understand, can you explain it in detail? This is the core function, I do not want to have a wrong understanding.  (I have seen the documentation for [Unit-Of-Work many times)

**Comment by hikalkan** [comment]
This is a library code. Why do you need to understand it? It just works. But I will try to explain a bit longer.

UnitOfWork attribute makes a method transactional. In Create, Delete and Move we have more than one database operation, so they should be transactional. Actually, since you will use this methods from an app service, it will be already transactional even we don't use the attribute. But we thought this can be called in an arbitrary method which is not in a active uow.

For Update, there is only single database operation which is already transactional by it's nature.

**Comment by maliming** [comment]
thanks. i got it.
