### ISSUE TITLE
Permission by URL

### ISSUE THREAD

**Issue by denisvirissimo** [aspnetboilerplate/module-zero#319]
Why not have permission check work by identifying if the role/user has the permission for the URL that is being called?
This way there would be no need to hard code the permissions.

**Comment by hikalkan** [comment]
A few reasons;

* It's so web specific way. Also, URLs can be changeable, but permission names are more static since they are related to application functionality.
* Same permission check may be needed for different web actions. Especially if you have a web app, a rest API and a mobile application.
* 2 URL can be actually related to single operation. Example: When editing an entity you may have 2 requests to 2 different URLs (first to get user edit info, second to update user). In that case these permissions should be grouped and activated/deactivated together.
* In some cases, URL can be called and the action may behave different based on permissions.

A Permission is a logical abstraction for application functionality, but URL is so technology-related and may not align to actual application functionalities.

**Comment by denisvirissimo** [comment]
Thanks for your responde, @hikalkan. Neve thought this way.
The only thing that bothers me is the hard coded names, but nothing we can deal with...

**Comment by hikalkan** [comment]
In future major versions, we will re-consider this if we can make simpler.
Thanks.
