### ISSUE TITLE
Support static and default permission

### ISSUE THREAD

**Issue by thrillertom** [aspnetboilerplate/module-zero#342]
As I know, Abp authorize with permissions, and host user and tenant user may have different permissions by default to make sure host users should not see tenant specific pages and vice verse.
So there may be always at least one permission for each multi-tenancy side, and user should not modifiy it(may be should not see it).
Abp supports default roles and assign them to the created user, but default roles don't have any permission, so the default roles should specify default permissions, what do you think?

**Comment by hikalkan** [comment]
You suggest that we define default permissions for tenants and hosts then you will use these permissions in your application? What type permissions are they? Why don't you that in your application?

**Comment by thrillertom** [comment]
I don't want some specific permissions, I want to define which permission is default. 
Now in Abp, I can define my default roles in my application. When I create a user, the application can tell which roles are default, then roles can be assign to user by programming. 
Just like roles, when I create a role, I may want to grant the role some permissions by default. But if I don't have a flag on permission to tell which one is default, I have to hard code the permission name.

**Comment by abou-emish** [comment]
I understand that you want to add a flag to permissions to set it as default, but default to which role ? you could have many roles and each role have it's own permissions...
You already have permissions hard coded, so in the place you seed system roles you will seed permissions for each of those roles.

**Comment by thrillertom** [comment]
@abou-emish Yes, just like you said, there may be many roles and each role have it's own permissions. I think it's the same thing between users and roles, there may be many users and each user have his own roles, when I define a default role, I don't have to specify a user. When I create  a user, I find out default roles and assign them to the user, but I don't have to hard code role name. Does it make sense?

**Comment by abou-emish** [comment]
Role is the top level of permissions, and role identity doesn't change from user to user, that's why you can set it as default or not, but permission is not top level and can be default to one role and not default to another role, your request doesn't need flag only, it needs also a flag and an array or roles which the permission is default for (and this will lead you to hard code roles names or Ids in the array)...

Much simpler is to seed initial or default permissions with each role as i said before.

**Comment by thrillertom** [comment]
@abou-emish As I know we can just use permission to identity user, roles may not be necessary in Abp, isn't it? And you are right if I want to define a default permission for each role, so is it possible to define default permission by multi-tenancy sides, because when I create a role, I should decide a multi-tenancy side.
There is also a static permission question, when some permissions are granted or not, we may not want user to change it any more. Maybe there are two permissions, one is **Host**, the other is **Tenants**, I grant **Host** to host users, and **Tenants** to tenant users, I use **Host** to prevent tenants user calling host apis and vice verse. So I may not allow user to change it, perhaps I can hard coded permission name when user want to change it and prevent it. But such permission could be 1...N, so maybe a flag can tell me about this information, what do you think about it?

**Comment by hikalkan** [comment]
Hi @thrillertom,

Let me explain why we created 'default role' concept: If you are creating user as admin, then you can easily select roles of this new user. But if you have a register form where users are registered themselves, then you have two options: 1) Don't assign any role. 2) Assign default role(s). We thought the second one is reasonable and created the default role concept.

For role-permission relation, there is no such a need because roles are always created by admins where they can easily select necessary permissions on role creation.
Instead of marking some permissions as 'default' (hard-coded), why not creating a default role (with default permissions) where it's assigned to all users. Then you can assign a second role to some users which you want to assign more permission. So, you can use existing mechanism to accomplish similar thing. Why do you think?

**Comment by thrillertom** [comment]
@hikalkan Sorry, you are right, I forgot a user could have more than one roles. Although, it may be a little weird that all users should have such a default role and should not remove it. But It does work.
Thank you for your time and help @abou-emish @hikalkan

**Comment by hikalkan** [comment]
Creating such a default role has such an advantage: You can then later add/remove a permission to that role. Otherwise, you must add the new permission to all roles when you want to define a new default permission.

**Comment by thrillertom** [comment]
@hikalkan 
Yes, you are right. It's easier to add a new default permission as you said. 
Here is the scenario, I define these roles **Admin**, **Manager**  and **Member**, I have the member as the default role and assign it to all users, so every user should have this role, but a manager user and admin user may feel strange, because they are already managers or admins, why should they have to keep a member role. This may be a literal meaning problem, because english is not my first language, I may not express it well, sorry for that, and thank you for your help.

**Comment by abou-emish** [comment]
You should share permissions among roles, and you don't have to keep user role for manager or admin, once you upgrade user to admin or manager you can remove user role, it's up to your system design. Abp is so flexible in this part :)

**Comment by thrillertom** [comment]
@abou-emish yes, I want to share permissions among roles at first, I will try to complete it in my own application. Thank you for your help.

**Comment by abou-emish** [comment]
Welcome :)
