### ISSUE TITLE
Roles property of User

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/module-zero#65]
As the property does not map `Role` directly it would be nice if this property would be renamed. Property named `Roles` should point to a collection of "Role" entity assigned to this user. Now property called `Roles` points to the entity that has just two keys in it.

**Comment by hikalkan** [comment]
This maybe hard to change now since there are many applications written :)

**Comment by easyest** [comment]
Indeed. For my purposes I have extended user roles relation entity with role navigational property and simply select user roles from this.
I am not closing this issue as it's up to You to make decision if such refactoring would give any benefits.

**Comment by Znow** [comment]
+1 on this one, or just add a navigation property for Role and User each, on the UserRole class?

Really can't understand why you have left this out @hikalkan , when this is some of the most essential part of your framework!

**Comment by hikalkan** [comment]
Because, Role and User are generics. If I add nav properties, then UserRole should be

    UserRole<TUser,TRole>

And we should inherit from it for our application. Then we should add another generic parameter to AbpZeroDbContext and UserManager and so on... When I designed that, I think that no need to such a complexity just to add a navigation property. Since this entity is rarely used, we can write some joins when we need...
That was the idea :)

**Comment by Znow** [comment]
It's really, alot easier and user friendly, to use navigation properties, to get roles for a user, rather than doing "some joins" :-)

**Comment by easyest** [comment]
Halil already explained - this would make much bigger overhead than benefits. I think I should close this issue.
