### ISSUE TITLE
How to set form into Angular view

### ISSUE THREAD

**Issue by Jerome2606** [aspnetboilerplate/module-zero#82]
Hi,

Before all, many thanks for your work. It's really imperssive !
I have a project using aspboilerplate (EF and AngularJs). I download your sample and I see that the authentification form is in an MVC view.
I try to implements a registration form and authentification form into angularJs.
Do you plan to implements this kind of feature in your project ? 
Do you have any advice where I can look for to achieve this ?

Best regards,

Jérôme

**Comment by hikalkan** [comment]
Hi,

Thank you.
There is no restriction here, you can create a new angular controller&view for that. But I advice to not include it to the main application. Create a new angular layout and module for that.
But, actually I suggest to not do that, no need it since login and registration pages are very simple and can be remain as MVC.
